### ISSUE TITLE
Windows image path

### ISSUE THREAD

**Issue by luftj** [cpietsch/vikus-viewer-script#5]
I get the following error in an downstream package when running the spritesheet script. Unfortunately the stacktrace is cropped, so I can't tell where it gets called. It seems the image path gets misinterpreted because of different slashes.
Occurs on Win10 with both PowerShell and bash.

```
> vikus-viewer-scripts@0.1.0 spritesheets C:\projects\vikus-viewer-script\images
> node spritesheets.js "-i" "$IMAGEPATH"

⠙ Error: Error: Command failed: Unzul�ssiger Parameter - /projects

at ChildProcess.onExit (C:\projects\vikus-viewer-script\images\node_modules\gm\lib\command.js:301:17)
at ChildProcess.emit (events.js:182:13)
at ChildProcess.cp.emit (C:\projects\vikus-viewer-script\images\node_modules\gm\node_modules\cross-spawn\lib\enoent.js:40:29)
at maybeClose (internal/child_process.js:962:16)
at Socket.stream.socket.on (internal/child_process.js:381:11)
at Socket.emit (events.js:182:13)
at Pipe._handle.close (net.js:610:12)
sprites generated sucessfully
⠙ Progressing - 345 remaining
```

Also when running as

`node spritesheets.js -i "/c/projects/vikus-viewer-script/images/data"`

**Comment by cpietsch** [comment]
Ok the error originates from gm (GraphicsMagick for node). What node version are you running?
Have you installed https://imagemagick.org/script/download.php ?

**Comment by thmensing** [comment]
I had the same worries. With your update on package.json, [Link](https://github.com/cpietsch/vikus-viewer-script/commit/9e7f480c68699253684827ab0e57721709235e55#diff-3f8338ad431c4db3372529d0791b0939), suddenly it worked.
At least with -s 128 and relative path as recommended: node spritesheets.js -s 128 -i /path/to/images

**Comment by mcbegp** [comment]
I had the same issue. However, executing this fixed it for me:

`node node_modules/optipng-bin/lib/install.js`

**Comment by cpietsch** [comment]
You can try out the [new script](https://github.com/cpietsch/vikus-viewer-script/tree/v2). Completely without GraphicsMagick or pixi-packer. And a lot faster.

**Comment by cpietsch** [comment]
can you report if this problem still exists in v2 ?
