### ISSUE TITLE
Trouble running on macOS HighSierra

### ISSUE THREAD

**Issue by liviupop** [cpietsch/vikus-viewer-script#6]
I have issues running the image script, it seems like the sharp module is missing. Here's a link to the log: https://www.dropbox.com/s/be32it0ohvh8kbt/2019-10-24T06_42_33_534Z-debug.log

Any ideas what to try? Thanks!

**Comment by liviupop** [comment]
The solution was to deinstall node -v 12 and install a node -v 10 like here: https://www.surrealcms.com/blog/how-to-upgrade-or-downgrade-nodejs-using-npm.html

Then I deleted the existing node_modules folder and used `nmp i` again.

**Comment by cpietsch** [comment]
Great that you got it working with node v10.
I looked into the issue and it appears that there is a problem with minipass: https://github.com/lovell/sharp/issues/1882#issuecomment-534472345
If you got time you could try the v0.23.1 of sharp and report back if it is working now.

**Comment by cpietsch** [comment]
this should be resolved by version 2
