### ISSUE TITLE
Sprites 2px too small?

### ISSUE THREAD

**Issue by mnscholz** [cpietsch/vikus-viewer-script#8]
I generated sprites using 
`IMAGEPATH=/path/to/images npm run build`
as indicated in the README.md.

When loading Vikus viewer no images are shown and the console logs an error for every sprite, saying something like this:
`Error: Texture Error: frame does not fit inside the base Texture dimensions: X: 0 + 258 = 258 > 2039 or Y: 1793 + 250 = 2043 > 2041`
For every sprite, either X or Y are 2px too small.
When I resize the sprites (manually), making them 2px larger, Vikus works fine.

Any hint what is going wrong and how to avoid this?

**Comment by cpietsch** [comment]
Thats indeed weird. What size are your input images ? Could you also post the spritesheets json ?

**Comment by mnscholz** [comment]
Attached you find the [web_web_full.json.txt](https://github.com/cpietsch/vikus-viewer-script/files/4180650/web_web_full.json.txt).

The original images are between 297 and 2197 px width and 307 and 1900 px height.

**Comment by cpietsch** [comment]
Currently VIKUS Viewer Script is using pixi-packer to generate the spritesheets which is quite out of date and got some issues.
In your JSON I can find the trim parameter per sprite. That might cause the problem.
Try running the scripts individually with the ``-s 128`` parameter to create smaller sprites.

I will be releasing my own spritesheet script in the next weeks. Stay tuned.

**Comment by cpietsch** [comment]
Any luck ? I am not sure how you got the `"trim": {
                        "x": -1,
                        "y": -1,
                        "w": 258,
                        "h": 119
                    }` into the spritesheet json. Have you changed some settings in images/spritesheets.js ?

**Comment by cpietsch** [comment]
There is now a [version 2 branch](https://github.com/cpietsch/vikus-viewer-script/tree/v2)
You might give it a try by pointing it to the tmp files `node .\bin\spritesheets.js .\data\tmp\256\ --outputFormat jpg`
